{% set name = "uWSGI" %}
{% set version = "2.0.19.1" %}
{% set sha256 = "faa85e053c0b1be4d5585b0858d3a511d2cd10201802e8676060fd0a109e5869" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py<36]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - icu
    - jansson
    - libxml2
    - openssl
    - pcre
    - yaml
    - zlib
  run:
    - python
    - jansson

test:
  source_files:
    - tests
  commands:
    - uwsgi --version
    - uwsgi --plugin-list

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.
